apiVersion: v1
kind: Pod
metadata:
  name: sys2
  labels:
    name: sys2-pod
spec:
  containers:
  - name: sysbench
    image: vadimtk/ubu-mysql-sysbench:latest
    imagePullPolicy: Always
    command: ["/bin/sh"]
    args: ["-c", "/usr/sbin/sshd -D; while true; do echo hello; sleep 10;done"]
  restartPolicy: OnFailure
  nodeSelector:
    kubernetes.io/hostname: "lke15505-18914-5fe0db684cea"
